apply from: rootProject.file('gradle/java-conventions.gradle')
apply plugin: 'java-test-fixtures'

description = 'Reads an OpenAPI spec into a Toolpool catalog.'

dependencies {
    api project(':libs:toolpool-core')
    api 'io.swagger.parser.v3:swagger-parser:2.1.46'
    implementation 'org.slf4j:slf4j-api'

    testFixturesApi project(':libs:toolpool-core')
}
