set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Run the toolpool-demo app, letting moon build libs:toolpool first
toolpool-demo:
    moon run toolpool-demo:run

# Run the default demo app
all: toolpool-demo
