set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Run the jopenapimcp test suite
jopenapimcp:
    moon run jopenapimcp:test

# Run the sample-rest-api-client test suite
sample-rest-api-client:
    ./gradlew :libs:sample-rest-api-client:test

# Run the jopenapi-demo test suite
jopenapi-demo:
    moon run jopenapi-demo:test

# Run every test suite
all: jopenapimcp sample-rest-api-client jopenapi-demo
