set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Run the jopenapimcp test suite
jopenapimcp:
    ./gradlew :libs:jopenapimcp:test

# Run the sample-rest-api-client test suite
sample-rest-api-client:
    ./gradlew :libs:sample-rest-api-client:test

# Run every test suite
all: jopenapimcp sample-rest-api-client
