plugins {
    id 'java-library'
    id 'checkstyle'
    id 'pmd'
}

group = 'io.github.flexksx'
version = '0.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server:2.0.0'
    implementation 'org.springframework.ai:spring-ai-starter-mcp-server-webmvc:2.0.0'

    implementation 'io.swagger.parser.v3:swagger-parser:2.1.46'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

pmd {
    toolVersion = '7.26.0'
    ruleSets = []
    ruleSetFiles = files('config/pmd/ruleset.xml')
    consoleOutput = true
    ignoreFailures = false
}

checkstyle {
    toolVersion = '14.0.0'
    configFile = file('config/checkstyle/checkstyle.xml')
    ignoreFailures = false
    maxWarnings = 0
}
