spring:
  application:
    name: toolpool-demo
  ai:
    mcp:
      server:
        enabled: true
        version: 1.0.0

toolpool:
  spec-location: ./openapi/sample-rest-api-client.openapi.json
  refresh-interval: 5m
