set working-directory := "../.."

[private]
default:
    just --list --justfile {{source_file()}}

# Format Nix files
nix:
    alejandra .

# Format Markdown files
markdown:
    rumdl check --fix .

# Run every formatter
all: nix markdown
